### ISSUE TITLE
any example how to use in cache configs?

### ISSUE THREAD

**Issue by eerison** [RikudouSage/DynamoDbCachePsr6Bundle#22]
I tried configure this bundle in

```
framework:
    cache:
        app: Rikudou\DynamoDbCacheBundle\Cache\DynamoDbCacheAdapter
```
But it doesn't work!

am I missing something?

**Comment by RikudouSage** [comment]
Unless something changed recently, it should be enough to configure `replace_default_adapter` in this bundle's config. Doesn't it work for you? I'm not sure right now how to do it without it (it's been a while since I've last configured it) but let me check.

**Comment by eerison** [comment]
I tried with 

```
framework:
    cache:
        app: Rikudou\DynamoDbCacheBundle\Cache\DynamoDbCacheAdapter
        system: Rikudou\DynamoDbCacheBundle\Cache\DynamoDbCacheAdapter
```

and I got this issue
```
Rikudou\DynamoDbCacheBundle\Cache\DynamoDbCacheAdapter::__construct(): Argument #1 ($cache) must be of type Rikudou\DynamoDbCache\DynamoDbCache, string given, called in /tmp/var/dev/cache/ContainerV76akFa/App_KernelDevDebugContainer.php on line 757
```

I'm using symfony 6

**Comment by eerison** [comment]
well in theory should appear something here besides the session, shouldn't it?

![Screenshot 2022-10-04 at 18 20 48](https://user-images.githubusercontent.com/6358755/193872733-f757cdaf-ea48-4eda-b018-cb0dd01231b6.png)

**Comment by eerison** [comment]
like a cache line 👀 

But even with this config `replace_default_adapter` true or false, nothing change

**Comment by RikudouSage** [comment]
Only if you actually use the cache. It might be a little confusing, because Symfony uses multiple types of cache, for example build cache that's available after you run `php bin/console cache:warmup`.

This is the app cache that you have to use yourself, here is an example controller:

```php
<?php

namespace App\Controller;

use Psr\Cache\CacheItemPoolInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

final class MainController extends AbstractController
{
    #[Route('')]
    public function index(CacheItemPoolInterface $cache)
    {
        $item = $cache->getItem('someItem');
        $item->set('someValue');
        $item->expiresAfter(30);

        return new JsonResponse([
            'success' => $cache->save($item),
        ]);
    }
}
```

Afterwards it looks like this in my DynamoDB table:

![Screenshot 2022-10-04 at 18-27-49 Items Amazon DynamoDB Management Console](https://user-images.githubusercontent.com/13106547/193874215-852812f0-0e45-4308-b03d-0b0f28570555.png)

**Comment by eerison** [comment]
yeah, I guess using manually it works, But I was thinking to use it in my symfony configs

> There are two pools that are always enabled by default. They are cache.app and cache.system. The system cache is used for things like annotations, serializer, and validation. The cache.app can be used in your code. You can configure which adapter (template) they use by using the app and system key like:


https://symfony.com/doc/current/cache.html#configuring-cache-with-frameworkbundle


But anyway, I can see how to use this, and if it's missing something I can open a PR ;)

**Comment by RikudouSage** [comment]
It more or less does the same. Anyway you would have to import the service somehow (for example using `CacheItemPoolInterface` class) and then use it. The `replace_default_adapter` basically means that you won't get `cache.app` when you ask for any of the interfaces but service from this bundle.

**Comment by eerison** [comment]
Well it's still not working for me :/

for some reason it's passing `string` in the first parameter: https://github.com/RikudouSage/DynamoDbCachePsr6Bundle/blob/master/src/Cache/DynamoDbCacheAdapter.php#L24

I removed the type hint and it's passing, this string `string(10) "iuCyXXsCl1"`, No idea why!

Where should be used this adapter?

**Comment by RikudouSage** [comment]
And this happens when you use `replace_default_adapter`? Or when you're trying to use it as an adapter for Symfony cache?

**Comment by eerison** [comment]
I tried with `replace_default_adapter` true and false and both return this same issue.

And it just happen if I try to use in my cache config.

**Comment by RikudouSage** [comment]
No idea how to do it, Symfony is either broken or undocumented in this regard and in both cases I don't really care as it's not my problem to solve.

If, for some reason, you want to use `cache.app` as the service name, just skip the whole Symfony cache config and do this in `services.yaml`:

```yaml
services:
    cache.app: '@rikudou.dynamo_cache.adapter'
```

Other than that there's really no need to involve the Symfony cache system at all. So unless you tell me what is it you want to achieve I'm afraid I cannot help any further.

**Comment by eerison** [comment]
Just to my understanding, for what propose was created this Adapter?
I don't see the user case into the docs

**Comment by RikudouSage** [comment]
To have your app cache in DynamoDB.

**Comment by eerison** [comment]
> So unless you tell me what is it you want to achieve I'm afraid I cannot help any further.

what I want to achieve is keep my whole application saving cache into DynamoDb!

But here you said that my application should be cached into there
But when I look into the DynamoDb I just see the `session` created, no cache entry I see 👀 
> To have your app cache in DynamoDB.

**Comment by RikudouSage** [comment]
Then skip the Symfony cache config in `cache.yaml` and do one of the following:

1. Enable `replace_default_adapter` in this bundle's config
2. Alias the `cache.app` service to `rikudou.dynamo_cache.adapter` in your `services.yaml` (see [here](https://github.com/RikudouSage/DynamoDbCachePsr6Bundle/issues/22#issuecomment-1269744825))

Both will make your default app cache be DynamoDB.

Note that there may be different cache pools, `app` is just the default for your application cache. I recall annotations using their own pool (`annotations`).

So instead of configuring it as an adapter in Symfony cache (which will basically create a service named `cache.[pool-name]`), create the service directly as alias to `rikudou.dynamo_cache.adapter`.

**Comment by eerison** [comment]
> Enable replace_default_adapter in this bundle's config

is it work in dev environment? maybe I'm doing something wrong because it definitely doesn't work

**Comment by RikudouSage** [comment]
Yes, but you have to use the cache as mentioned [here](https://github.com/RikudouSage/DynamoDbCachePsr6Bundle/issues/22#issuecomment-1267262636).

The cache is empty for you, because you don't use the cache. There cannot be anything if you don't use it. The `cache.app` is only populated when your app stores something there. The `cache.system`. If you mean the build cache after running for example `cache:clear`, then this cache will be on the filesystem, not in DynamoDB. And you should leave it on the filesystem. In production this build cache won't be updated at all (obviously only if you pregenerate it) so it can even be on a read-only filesystem. So leave the build cache on the filesystem and use the adapter only your app cache.

**Comment by eerison** [comment]
> Yes, but you have to use the cache as mentioned [here](https://github.com/RikudouSage/DynamoDbCachePsr6Bundle/issues/22#issuecomment-1267262636).
> 
> The cache is empty for you, because you don't use the cache. There cannot be anything if you don't use it. The `cache.app` is only populated when your app stores something there. If you mean the build cache after running for example `cache:clear`, then this cache will be on the filesystem, not in DynamoDB. And you should leave it on the filesystem. In production this build cache won't be updated at all (obviously only if you pregenerate it) so it can even be on a read-only filesystem. So leave the build cache on the filesystem and use the adapter only your app cache.

Ahh ok I got it!

**Comment by tyx** [comment]
Hello ! 

As I faced the same issue, just a quick message to show the final solution:

```yaml
framework:
  cache:
    pools:
      my_dynamodb_pool:
        default_lifetime: 3600
        adapters:
          - cache.adapter.array
          - {
              name: cache.adapter.psr6,
              provider: 'rikudou.dynamo_cache.adapter',
            }
```

I can add a few word about it in the README if you want.

Thanks for your work anyway !

**Comment by RikudouSage** [comment]
@tyx Sure, I welcome a PR!
